services:
  keycloak:
    image: quay.io/keycloak/keycloak:18.0
    container_name: keycloak_service
    command: ['start-dev', '--import-realm']
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: 'true'
      KC_HOSTNAME_STRICT: 'false'
    ports:
      - "8180:8080"
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
      - keycloak_data:/opt/keycloak/data
    networks:
      - employee-net
    restart: unless-stopped

  opa:
    image: openpolicyagent/opa:latest
    container_name: opa_service
    command:
      - "run"
      - "--server"
      - "--addr=0.0.0.0:8181"
      - "--watch"
      - "--log-level=debug"
      - "--log-format=json-pretty"
      - "/policies"
    ports:
      - "8181:8181"
    volumes:
      - ./opa/policies:/policies   # mount local policies directory
    networks:
      - employee-net
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8181/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  employee-net:
    driver: bridge

volumes:
  keycloak_data:
